# Generated by Django 5.1.5 on 2025-04-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='image_url',
        ),
    ]
