# Generated by Django 5.1.5 on 2025-04-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0005_couple_creation_date_userprofile_is_in_couple_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
