# Generated by Django 5.1.5 on 2025-04-17 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0006_remove_userprofile_image_url_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_in_couple',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
