# Generated by Django 5.1.5 on 2025-04-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0008_alter_couple_creation_date_alter_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='responded',
        ),
    ]
