# Generated by Django 5.1.5 on 2025-04-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0011_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
