# Generated by Django 5.1.5 on 2025-04-29 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0012_userprofile_latitude_userprofile_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='couple_images/')),
                ('caption', models.TextField(blank=True)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalproject.couple')),
            ],
        ),
        migrations.CreateModel(
            name='CouplePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalproject.couple')),
            ],
        ),
        migrations.CreateModel(
            name='CouplePostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalproject.coupleimage')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalproject.couplepost')),
            ],
        ),
    ]
