# Generated by Django 5.1.5 on 2025-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('Street_Number', models.IntegerField()),
                ('Street_Name', models.TextField()),
                ('Apartment_Number', models.IntegerField()),
                ('Zip_Code', models.IntegerField()),
                ('DOB', models.DateField()),
                ('DOR', models.DateField()),
                ('Party', models.TextField()),
                ('Precinct_Number', models.IntegerField()),
                ('Voter_Score', models.IntegerField()),
                ('v20state', models.TextField()),
                ('v21town', models.TextField()),
                ('v21primary', models.TextField()),
                ('v22general', models.TextField()),
                ('v23town', models.TextField()),
            ],
        ),
    ]
