# Generated by Django 5.1.5 on 2025-04-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='Precinct_Number',
            field=models.TextField(),
        ),
    ]
