# Generated by Django 5.1.5 on 2025-04-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0004_alter_voter_voter_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='Voter_Score',
            field=models.IntegerField(),
        ),
    ]
